# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'docker/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cline-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cline-backend:latest'
      - '.'
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/cline-backend'
    id: 'push-image'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cline-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cline-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--timeout'
      - '${_TIMEOUT}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--update-env-vars'
      - 'WORKSPACE_DIR=/workspaces,CLINE_DIR=/root/.cline'
    id: 'deploy-cloud-run'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cline-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cline-backend:latest'

# Substitution variables (can be overridden)
substitutions:
  _REGION: us-central1
  _MEMORY: 2Gi
  _CPU: '2'
  _TIMEOUT: 300
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

